import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { cn } from "@/utils";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn(roboto.className, "bg-gray-900 bg-app bg-no-repeat bg-cover")}>{children}</body>
    </html>
  );
}
